### ISSUE TITLE
Can a more linux-friendly format be provided?

### ISSUE THREAD

**Issue by GanerCodes** [talhahasanzia/English-Thesaurus#1]
I'd much prefer a SQLLite database or just a plain CSV for this, as I can't actually open this file without paying some service to convert it

**Comment by talhahasanzia** [comment]
Hi, I will look into this and find a solution, this was years back 🙂

**Comment by talhahasanzia** [comment]
@GanerCodes It is now available as plain csv. I had to go through multiple installation and upgrades to make db files work, but it was fun exercise. This was university project and I didnt cared much about vendor locking back then :)

**Comment by GanerCodes** [comment]
<3 Thanks :>

**Comment by talhahasanzia** [comment]
@GanerCodes updated csv with removed duplicates and some unicode garbage characters :)

If possible, can you share the project in what you need this? 
If its on github or open source I might also mention it in this repo's readme :)

**Comment by GanerCodes** [comment]
Ah, not to disappoint but the project was really small in scale. Just a quick script I made for fun to scramble around word
[main.txt](https://github.com/talhahasanzia/English-Thesaurus/files/9457564/main.txt)
s
